name: Convert_the_Ruleset_file_into_Domainset_file

# 触发条件
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟执行一次

jobs:
  process_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Process Shadowrocket Ruleset File
        run: |
          # 定义要处理的文件名
          file="adblock_reject_shadowrocket_ruleset.conf"
          # 生成目标文件名 (将 ruleset 替换为 domainset)
          output_file=$(echo "$file" | sed 's/ruleset/domainset/')
          # 处理文件：
          # 1. 保留注释和 "payload:"，只删除 "DOMAIN,"
          # 2. 将注释中的 "RULE-SET" 替换为 "DOMAIN-SET"
          # 3. 将注释中的 "RULESET" 替换为 "DOMAINSET"
          sed -E 's/DOMAIN,//g; s/RULE-SET/DOMAIN-SET/g; s/RULESET/DOMAINSET/g' "$file" > "$output_file"

      - name: Commit and Push Changes
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # 添加处理后的文件
          git add adblock_reject_shadowrocket_domainset.conf

          # 提交更改或进行空提交以保持工作流运行
          git commit -m "Processed and generated Shadowrocket domainset file" || git commit --allow-empty -m "No changes, empty commit to keep the workflow running"

          # 强制推送
          git push --force "https://${TOKEN}@github.com/${{ github.repository }}.git" HEAD:main
