name: Trigger in sequence

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟触发一次

jobs:
  trigger_adblock_rule_generator_shadowrocket_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出仓库代码

      - name: Trigger and verify Run_AdBlock_Rule_Generator_Shadowrocket_Yaml
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Run_AdBlock_Rule_Generator_Shadowrocket_Yaml.yml"
          ref="main"
          # 触发工作流
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id: $response"

          # 验证工作流成功触发
          while : ; do
            status=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$status" == "success" ]]; then
              echo "Workflow $workflow_id completed successfully."
              break
            elif [[ "$status" == "failure" ]]; then
              echo "Workflow $workflow_id failed."
              exit 1
            else
              echo "Waiting for workflow $workflow_id to complete..."
              sleep 30
            fi
          done

          # 等待90秒
          sleep 90

  trigger_adblock_rule_generator_txt:
    runs-on: ubuntu-latest
    needs: trigger_adblock_rule_generator_shadowrocket_yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出仓库代码

      - name: Trigger and verify Run_AdBlock_Rule_Generator_TXT
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Run_AdBlock_Rule_Generator_TXT.yml"
          ref="main"
          # 触发工作流
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id: $response"

          # 验证工作流成功触发
          while : ; do
            status=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$status" == "success" ]]; then
              echo "Workflow $workflow_id completed successfully."
              break
            elif [[ "$status" == "failure" ]]; then
              echo "Workflow $workflow_id failed."
              exit 1
            else
              echo "Waiting for workflow $workflow_id to complete..."
              sleep 30
            fi
          done

          # 等待90秒
          sleep 90

  trigger_adblock_rule_generator_list:
    runs-on: ubuntu-latest
    needs: trigger_adblock_rule_generator_txt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出仓库代码

      - name: Trigger and verify Run_AdBlock_Rule_Generator_LIST
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Run_AdBlock_Rule_Generator_LIST.yml"
          ref="main"
          # 触发工作流
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id: $response"

          # 验证工作流成功触发
          while : ; do
            status=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$status" == "success" ]]; then
              echo "Workflow $workflow_id completed successfully."
              break
            elif [[ "$status" == "failure" ]]; then
              echo "Workflow $workflow_id failed."
              exit 1
            else
              echo "Waiting for workflow $workflow_id to complete..."
              sleep 30
            fi
          done

          # 等待90秒
          sleep 90

  trigger_adblock_rule_generator_yaml:
    runs-on: ubuntu-latest
    needs: trigger_adblock_rule_generator_list
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出仓库代码

      - name: Trigger and verify Run_AdBlock_Rule_Generator_YAML
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Run_AdBlock_Rule_Generator_YAML.yml"
          ref="main"
          # 触发工作流
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id: $response"

          # 验证工作流成功触发
          while : ; do
            status=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$status" == "success" ]]; then
              echo "Workflow $workflow_id completed successfully."
              break
            elif [[ "$status" == "failure" ]]; then
              echo "Workflow $workflow_id failed."
              exit 1
            else
              echo "Waiting for workflow $workflow_id to complete..."
              sleep 30
            fi
          done

          # 等待90秒
          sleep 90

  trigger_release_adblock_files:
    runs-on: ubuntu-latest
    needs: trigger_adblock_rule_generator_yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出仓库代码

      - name: Trigger and verify Release_ADblock_Files
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Release_ADblock_Files.yml"
          ref="main"
          # 触发工作流
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id: $response"

          # 验证工作流成功触发
          while : ; do
            status=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Shadowrocket/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$status" == "success" ]]; then
              echo "Workflow $workflow_id completed successfully."
              break
            elif [[ "$status" == "failure" ]]; then
              echo "Workflow $workflow_id failed."
              exit 1
            else
              echo "Waiting for workflow $workflow_id to complete..."
              sleep 30
            fi
          done

          # 等待90秒
          sleep 90

  check_all_workflows:
    runs-on: ubuntu-latest
    needs: 
      - trigger_adblock_rule_generator_shadowrocket_yaml
      - trigger_adblock_rule_generator_txt
      - trigger_adblock_rule_generator_list
      - trigger_adblock_rule_generator_yaml
      - trigger_release_adblock_files
    steps:
      - name: Ensure all workflows succeeded
        run: |
          echo "All workflows completed successfully"
